### ISSUE TITLE
Tilesets

### ISSUE THREAD

**Issue by kreativmonkey** [GaffaOverflow/gaffamap#10]
Ist es notwendig die anderen Tiles noch vor zu halten oder können  diese sowie die Credits weg?

Des Weiteren wäre es schön wenn @MakeNModify was zur Lizenz seiner tiles sagt.

**Comment by StirlingDe** [comment]
Afaik verlangen gewisse Tilesets das erwähnen in den Credits. Aktuell wäre es somit am besten, jene erstmal auf Vorrat zu behalten, solange wir noch die Tilesets verwenden

**Comment by MakeNModify** [comment]
Prinzipiell kann man versuchen das nur mit unseren eigenen Tiles zu machen, allerdings weiß ich nicht ob ichs schaffe rechtzeitig genug zu machen. Es wäre sinnvoll, wenn wir ein "Backupset" hätten zum Füllen von Lücken. Und ich kann die nach und nach durch eigene ersetzen. Zur Lizenz siehe meine Kommentar in #11
