### ISSUE TITLE
Sammlung für PCB-Gegenstände

### ISSUE THREAD

**Issue by foorschtbar** [GaffaOverflow/gaffamap#12]
- [x] [HD44780](http://vascoferraz.com/wp-content/tutorials/Hitachi-HD44780-LCD/Hitachi-HD44780-LCD_bb.png)
- [x] [Kondenstatoren](http://image.made-in-china.com/2f0j00FLEYUhZKECkn/Monolithic-Ceramic-Capacitor-104.webp)
- [x] ElKo's
- [ ] [Sieben Segment Anzeige](https://42project.net/wp-content/uploads/2017/04/7-Segmentanzeige-LED-Anzeige-Display-mit-Punkt-und-gemeinsamer-Kathode-rot-an.jpg)
- [x] Flachbandkabel grau (rot/blaue Linie für "Pin 1")
- [x] [LED](http://troybaverstock.com/wp-content/uploads/2019/04/arduino-servo-button-red-green-RGB-LED-wiring-diagram.png)
- [x] [ESP](https://d3s5r33r268y59.cloudfront.net/7853/products/thumbs/2015-04-16T12:23:07.642Z-2015-04-17%2000.56.14.jpg.2560x2560_q85.jpg)
- [x] [Taster](http://troybaverstock.com/wp-content/uploads/2019/04/arduino-servo-button-red-green-RGB-LED-wiring-diagram.png)
- [x] [Buzzer](https://rcexplorer.se/wp-content/uploads/2016/02/Beeper1.jpg)
- [x] [DIP-Schalter](https://cdn-reichelt.de/bilder/web/xxl_ws/C200/NT_10.png)
-  [ ] [Relais](https://opencircuit.shop/resources/content/dba291c271516/crop/1200-630/Relais-5V.jpg)
- [x] [OLED ](https://i.ebayimg.com/images/g/OoQAAOSwYSlXg3Ab/s-l1600.jpg)

**Comment by raroe** [comment]
- Quadratisches Gafferteil um 45 Grad gedreht ( neun Tiles?)

**Comment by MakeNModify** [comment]
Ein Hinweis für die Tiles: 1 Pixel entspricht 0,3175mm in der Realität!

Ergibt sich daraus, dass unser Raster 4 "Felder" auf 32 Pixel hat. Ein Feld hat 2,54mm (0.1'') => 2,54mm*4/32px=0,3175mm/px.
Dies gilt natürlich nur als Richtwert und soll zur Orientierung helfen ;)

**Comment by raroe** [comment]
einen kleinen Lautsprecher
ein paar bunte Einzeldrähte zum Stecken auf Breadboard und Platinen oder zum freien verkabeln(rot, blau gelb,grün, schwarz)

Wäre schön :-)

**Comment by foorschtbar** [comment]
Elemente angelehnt an offizellen Designguide:
- [ ] Ethernet Port als "Stargate"
- [ ] ...

**Comment by StirlingDe** [comment]
- [ ] ESP8266: Beliebig skalierbar in Breite und Länge (Vielleicht für auf ein PCB?)

- [ ] PCB-Platine mit Leiterbahnen (und Löchern)

- [ ] Lichterkette zum überhängen von Teilen (erweiterbar; Vielleicht an Zahnstochern aufhängbar)

- [ ] Zahnstocher für in PCB-Löcher

- [ ] Girlanden für an Zahnstocher 

Wären cool :)

**Comment by MakeNModify** [comment]
- [ ] Logos für Spaces (für OLEDs und Wände)
