### ISSUE TITLE
Tiled Master Map Dokument erstellen

### ISSUE THREAD

**Issue by MakeNModify** [GaffaOverflow/gaffamap#13]
Wir benötigen eine Example-Map die alle für den Bau ihrer Karten verwenden können. Diese Map haben wir wie folgt definiert:

	Layer:
	- silent
		Unterhaltungen bei Begegnung sind hier deaktiviert	
	- Bridge
		Dinge die den Spieler verdecken (Beispiel Lichterkette)
	- floorLayer (objet layer)
		Für Programm notwendig. Die Ebene auf der sich die Spielfigur befindet.
		Was darüber liegt verdeckt die Spielfigur, was darunter liegt ist unter dem Spieler.
	- start
		wenn dort ein Tile liegt ist das der Startpunkt für die Map.
		Liegen dort mehrere Tiles, entscheidet der Zufall auf welchem davon man startet.
	- Objects_Top
		wird überwiegend leer bleiben. Wird nur verwendet, wenn Objekte auf Objekten plaziert werden sollen (z.B. eine Kerze auf einem Tisch)
	- Objects_Bottom
		Objekte wie Tische/ICs, Widerstände aber auch alle Wände befinden sich auf dieser Ebene
	- Routes
		Wege zur Verbindung von Räumen/PCBs (Flachbandkabel, Gaffa)
	- Base
		Boden der Räume (PCBs)
	- Background
		Hintergrund (unterste Ebene) befindet sich unterhalb der Räume und ist der sonst nicht weiter definierte Raum 
	- Interactive (benötigt noch Tests, übernimmt Rainer)
		Hier können Tiles platziert werden die z.B. Webseiten aufrufen, 
	- Collision
		Tiles auf dieser Ebene definieren punkte die der Spieler nicht passieren kann (z.B. für Wände). Die Tiles müssen die Eigentschaft "collides = true" haben.
		Hinweis: Man kann zunächst durch alles durch laufen, bis es auf dieser Ebene blockiert wird.
		Hinweis2: kann während der Entwicklung weiter oben plaziert werden um die Blockierten stellen einfacher zu definieren.

Die Tiled-Mastermap wird von @raroe angefertigt.

**Comment by raroe** [comment]
Verzeichnis maps mit Master Template und Testbeispiel erstellt
