### ISSUE TITLE
Verantwortlichkeit Mapteile festlegen

### ISSUE THREAD

**Issue by MakeNModify** [GaffaOverflow/gaffamap#14]
Der Plan sieht vor dass wir eine große Karte aufbauen mit einem Hauptraum und "Nebenräumen" für einzelnen Spaces.
Dies soll sich alles auf einer großen Karte abspielen. 

Wer welchen Teil der Map herstellt ist noch nicht festgelegt, sollte allerdings zeitnah geschehen.

Im Idealfall kann dann jeder an einem Dokument arbeiten und diese missen zum Schluss "nur noch" zusammengefügt werden.

**Comment by kreativmonkey** [comment]
Ich würde gerne einen Teil übernehmen jedoch gehöre ich nicht direkt zu einem Space und würde mich somit den Nebenräumen oder dem Hauptraum wittmen wollen.

**Comment by kreativmonkey** [comment]
Schade, dachte hier wird die Aufteilung kommuniziert...

**Comment by MakeNModify** [comment]
Das wäre wohl gut gewesen... Ich guck heute Abend mal... Nachdem ich gestern früher gehen musste hab ich jetzt auch keinen Überblick und gab wohl keine Zusammenfassung...
