### ISSUE TITLE
TOPs für Map-Meeting am 8.Dez 20.00 Uhr

### ISSUE THREAD

**Issue by raroe** [GaffaOverflow/gaffamap#17]
# TOPs 

##  1. Mastermap

- Verabschiedung Mastermap
Die Mastermap und Beispiele liegen mit Beschreibung in src/maps vor

## 2.Tides

- Festlegung welche Tilesets wie genutzt werden
Mittlerweile liegen vom CCC auch Tidesets und weitere Gestaltungsempfehlungen vor 

## 3. Festlegung und Start mit Grundaufbau

ggf Festlegung einer Minimalkonfiguration  
Anlegen der Produktivmap in der ersten Version, Festlegung Workflow

**Comment by loppermann-de** [comment]
Unter https://westwoodlabs.pads.ccc.de/rc3-map ist eine Liste der Räume und wer was machen will.

**Comment by loppermann-de** [comment]
Die Räume werden einzellen gestalltet und zum schluss zusammen geführt.
Tides nutzen wir ersteinmal unsere.

**Comment by loppermann-de** [comment]
@niyawe baut ein skript zum zusammen bauen der Karte
