### ISSUE TITLE
Raumteil Lobby

### ISSUE THREAD

**Issue by loppermann-de** [GaffaOverflow/gaffamap#19]

**Comment by StirlingDe** [comment]
1. Ideen-Sammlung Lobby

- Ein großer Tisch mit Jitsi Lobby
- Verweis auf die einzelnen Spaces

2. Produktivsetzung
- [ ] Ein großer Tisch als Fokus mit Jitsi Lobby

- [ ] Verweis auf Spaces:
-- [ ] Webseiten Verweis haxko
-- [ ] Webseiten Verweis Westweedlabs
-- [ ] Webseiten Verweis ChaosOsna

**Comment by kreativmonkey** [comment]
Gibt es nähere Informationen? Welches Bauteil soll denn als Tisch fungieren oder ist die Lobby noch nicht im geplanten Style?

**Comment by StirlingDe** [comment]
Update:
Das Lobby-Design ist fertig und steht unter Maps als "lobby" zum Review zur Verfügung

**Comment by kreativmonkey** [comment]
Ich plädiere für ein Pizzapad am Pizzaofen

**Comment by kreativmonkey** [comment]
Könnte man die Wiederstände vor den Konferenzteil verschieben oder erweitern? Aktuell nervt es ein wenig das man ausversehen in den Konferenzbereich kommt, so müsste man gezielt zwischen den Wiederständen in den bereich eintreten.


![Wiederstände](https://user-images.githubusercontent.com/8607439/102722795-d310f980-4303-11eb-991d-2d8108572bd3.png)

**Comment by foorschtbar** [comment]
Mich stört es auch beim Vorbeilaufen. Wieso hat die Lobby überhaupt Jitsi's? Dafür haben wir doch die beiden Meeting- und den Vortragsraum. _**IHMO** sind die beiden in der Lobby überflüssig._

![2020-12-21 14_47_22-rC3 World _ Remote Chaos Experience 2020](https://user-images.githubusercontent.com/10727275/102783823-d0fa7980-439b-11eb-92e6-377058283121.png)

**Comment by StirlingDe** [comment]
> Mich stört es auch beim Vorbeilaufen. Wieso hat die Lobby überhaupt Jitsi's? Dafür haben wir doch die beiden Meeting- und den Vortragsraum. _**IHMO** sind die beiden in der Lobby überflüssig._
> 
> ![2020-12-21 14_47_22-rC3 World _ Remote Chaos Experience 2020](https://user-images.githubusercontent.com/10727275/102783823-d0fa7980-439b-11eb-92e6-377058283121.png)

Der Eingang sollte eigentlich nicht dort sitzen. Ich schaue mir mal an, wo das Problem liegt.
Die Jitsi-Konferenz dient als Pool für alle die einfach auf dem Server sind und einfach nur "da sein" wollen.
Die Meeting-Räume sind für Vorträge oder große Gruppen gedacht :)

**Comment by StirlingDe** [comment]
Das Problem für den Meeting-Raum wurde gefunde:
Jemand hat an der Lobby rumgepfuscht ohne mir Bescheid zu geben.
Werde den Eingang jetzt löschen und versetzen
