### ISSUE TITLE
Raumteil Museums

### ISSUE THREAD

**Issue by loppermann-de** [GaffaOverflow/gaffamap#21]

**Comment by kreativmonkey** [comment]
Gibt es dafür auch irgendwie ne Vorlage oder nen Text wie es in etwar aussehen kann damit man sich bei der Umsetzung beteiligen kann?

**Comment by MakeNModify** [comment]
Also meine Idee ist einen Raum zu machen in dem z.B. Tische (große ICs) sind und auf denen Gegenstände liegen. Nähert man sich öffnet sich eine Website. Das kann dann so etwas w.z.B [https://haxko.space/projekte/lightpainting/](haxko Lightpainting) sein, oder etwas wo andere Teilnehmer ihre Projekte vorstellen.
