### ISSUE TITLE
Raumteil Adventure-Raum

### ISSUE THREAD

**Issue by loppermann-de** [GaffaOverflow/gaffamap#25]

**Comment by raroe** [comment]
# Adventure-Raum

Dieser Raum - Arbeitsname "Adventure" - soll unterschiedliche Informationen und Aktionen anbieten. Je nach Angeboten kann sich der Name noch ändern.

Ich plane folgendes zu realisieren:

- Bezug zu GaffaOverflow durch virtuelles Anpappen der Bodenplatine an die "Wand" (muss im Gesamtbild noch geprüft werden, ob es gut aussieht)

- Information des Besuchers generell durch Audio-Ansprache

- Gate "Oleds" für den Switch zu Webseiten mit Text ,Video oder eigenen kleinen Spielen oder beam zu zusätzlichen Maps

- Vor den "Oleds" stehend, wird dem Besucher angesagt was ihn erwartet 

- im Raum ist normale Konversation der Besucher möglich (max 5 im Kreis)

- es gibt eine kleine Ruhezone 

Ich werde Zwischenschritte in[ /maps](https://github.com/GaffaOverflow/gaffamap/tree/main/src/maps) temporär  mit **adventure( _number_ ).json** speichern. Die nächste Iteration wird dann durch Erhöhung der Nummer im Dateinamen erreicht.

**So ein Raum lebt von den "Angeboten"! Wenn ihr Content habt, sprecht mich an, vielleicht  ist es geeignet und wir werden es visualisieren.**

Ablauf:

1.  Ermitteln der Raumgröße, Konzept Basislayer, Audiokonzept  ........................................    **_adventure1.json_**

**Comment by raroe** [comment]
Erstanlage

**Comment by raroe** [comment]
2. Test der Raumgröße, Konzept Grundaufbau, Audiokonzept ........................................ adventure2.json

Es werden testweise Tiles aus temporären eigenen den rc3-sets genutzt. Diese werden später  ggf ersetzt

**Comment by raroe** [comment]
3.  Audio, Räume , und Zugang zum Raum angepasst. Erfolgreicher Test mit Merge-Tool, Position zu Lobby angepaßt.  ............. adventure3.json
nächste Schritte:
Feinanpassung Komponenten und Test
Audios in Roboterstimmen wandeln, eindeutige Audioorte bestimmen
Content für Webaufrufe auswählen und verlinken
Text - Hinweise und Klimbim (raumschmuck) ggf animierte lookaways einbauen
