### ISSUE TITLE
Rätsel für badges

### ISSUE THREAD

**Issue by kreativmonkey** [GaffaOverflow/gaffamap#27]
Im Chat kam die Idee das wir uns an dem Badge Belohnungssystem beteiligen könnten. Eine Möglichkeit wäre absichtliche Fehler in die Karte zu integrieren die die Besucher dann finden müssen.

> https://events.ccc.de/2020/12/05/rc3-virtueller-aufbau/
"Da wir dieses Jahr nicht einfach in großen Sticker-Kisten wühlen können, bietet die Plattform mit einem Badge-System ein Ersatzkonzept zur Befriedigung des Jäger:innen- und Sammler:innen-Triebs. Als Assembly könnt Ihr Badges in zwei Modi anlegen: 
> - Sticker-Modus: zum einfach bei Euch Abholen
> - Achievement-Modus: Ihr als Assembly entscheidet ob/wie man es bekommt, z.B. nach einem Rätsel"

Dieses Issue ist nur zur Klärung ob wir dies so umsetzen wollen oder nicht. Die Lösungen sollten nicht öffentlich festgehalten werden ;-)

**Comment by loppermann-de** [comment]
es gibt jetzt ein badge beim betretten. Danke @MakeNModify @StirlingDe
