### ISSUE TITLE
Topologie fehler

### ISSUE THREAD

**Issue by kreativmonkey** [GaffaOverflow/gaffamap#3]
Wenn man einen Space betritt oder verlässt dann landet man immer in der "mitte" der Karte und nicht am jeweiligen "Eingang/Ausgang". Auch sind alle Spaces zwar in der Lobby verteilt aber von der räumlichen Aufteilung gleich, sprich der Ausgang ist oben und der Chatraum ist links, hier wäre es sicher schöner den Chatraum gegenüber des Eingangs/Ausgangs zu machen und diesen jeweils nach der Lage in der Lobby zu verteilen.

**Comment by kreativmonkey** [comment]
Das scheint ein Bug von der Instanz zu sein, die Karte macht [laut Guid](https://workadventu.re/create-map.html#defining-several-entry-points) alles richtig, auch ein umbauen der Karte hilft da nicht....

**Comment by foorschtbar** [comment]
Ist mir auf aufgefallen!
