### ISSUE TITLE
Beschriftungen

### ISSUE THREAD

**Issue by MakeNModify** [GaffaOverflow/gaffamap#33]
Ich werde ein Tileset erstellen auf dem Tiles für Beschriftungen sind. Aktuell habe ich vor 2 Versionen von jedem Schild zu erstellen:
- "Sikscreen" Versin (PCB Aufdruck)
- "Lable" Version (wie aus einem Lablewriter)

Jeder dann sich hier etwas wünschen wenn er/sie noch etwas braucht.
Aktuelle geplant:

- [x] Info
- [x] Silent Room
- [x] Jitsi

**Comment by raroe** [comment]
- [ ] music
- [ ] audio
- [ ] talk together
wäre schön
