### ISSUE TITLE
Easteregg?

### ISSUE THREAD

**Issue by kreativmonkey** [GaffaOverflow/gaffamap#4]
Wie wäre es mit einem Easteregg auf der Karte? Man könnte zum beispiel irgendwo einen "Ausgang" verstecken und landet dann zum Beispiel in der Streamingküche, also einen "geheimen" Raum.

**Comment by TimKlausmeyer** [comment]
Ja sowas fänd ich witzig :)

**Comment by loppermann-de** [comment]
wurde nicht umgesetzt
